/*(MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL,
NBR_MMSC_FWR_TO_OTHER_MMSC,
NBR_MMSC_FWR_REC_FROM_MMSC,
NBR_TERM_TO_TERM,
NBR_TERM_TO_APP,
TIME_OF_PERIOD,
FECHA_PROC)*/

declare
  FECHA_PROC varchar2(8 char) := '20170319';
begin
--TRUNCATE TABLE MMSC_SERVICE_ZTE_TMP;

INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL,NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'00:00 ~ 01:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'01:00 ~ 02:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'02:00 ~ 03:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'03:00 ~ 04:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'04:00 ~ 05:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'05:00 ~ 06:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'06:00 ~ 07:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'07:00 ~ 08:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'08:00 ~ 09:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'09:00 ~ 10:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'10:00 ~ 11:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'11:00 ~ 12:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'12:00 ~ 13:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'13:00 ~ 14:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'14:00 ~ 15:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'15:00 ~ 16:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'16:00 ~ 17:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'17:00 ~ 18:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'18:00 ~ 19:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'19:00 ~ 20:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'20:00 ~ 21:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'21:00 ~ 22:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'22:00 ~ 23:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','ARG',0,0,0,0,0,0,0,0,'23:00 ~ 00:00','${FECHA_PROC}');
--
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL,NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'00:00 ~ 01:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'01:00 ~ 02:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'02:00 ~ 03:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'03:00 ~ 04:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'04:00 ~ 05:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'05:00 ~ 06:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'06:00 ~ 07:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'07:00 ~ 08:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'08:00 ~ 09:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'09:00 ~ 10:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'10:00 ~ 11:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'11:00 ~ 12:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'12:00 ~ 13:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'13:00 ~ 14:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'14:00 ~ 15:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'15:00 ~ 16:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'16:00 ~ 17:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'17:00 ~ 18:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'18:00 ~ 19:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'19:00 ~ 20:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'20:00 ~ 21:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'21:00 ~ 22:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'22:00 ~ 23:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','UY',0,0,0,0,0,0,0,0,'23:00 ~ 00:00','${FECHA_PROC}');
--
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL,NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'00:00 ~ 01:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'01:00 ~ 02:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'02:00 ~ 03:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'03:00 ~ 04:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'04:00 ~ 05:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'05:00 ~ 06:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'06:00 ~ 07:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'07:00 ~ 08:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'08:00 ~ 09:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'09:00 ~ 10:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'10:00 ~ 11:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'11:00 ~ 12:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'12:00 ~ 13:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'13:00 ~ 14:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'14:00 ~ 15:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'15:00 ~ 16:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'16:00 ~ 17:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'17:00 ~ 18:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'18:00 ~ 19:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'19:00 ~ 20:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'20:00 ~ 21:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'21:00 ~ 22:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'22:00 ~ 23:00','${FECHA_PROC}');
INSERT INTO MMSC_SERVICE_ZTE_TMP (MMSC,PAIS,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL, NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) VALUES ('Local MMSC','PY',0,0,0,0,0,0,0,0,'23:00 ~ 00:00','${FECHA_PROC}');

end;
--
-- TEMPLATE TABLE
--
DROP TABLE MMSC_SERVICE_ZTE_TMP PURGE;
CREATE TABLE MMSC_SERVICE_ZTE_TMP (
FECHA                         DATE GENERATED ALWAYS AS (TO_DATE(
                                                        SUBSTR(FECHA_PROC,7,2) ||'.'||
                                                        SUBSTR(FECHA_PROC,5,2) ||'.'||
                                                        SUBSTR(FECHA_PROC,1,4) ||' '||
                                                        SUBSTR(TIME_OF_PERIOD,1,5),'DD.MM.YYYY HH24:MI')-1) VIRTUAL,
PAIS                          VARCHAR2(3 CHAR) NOT NULL,
MMSC                          VARCHAR2(10 CHAR) NOT NULL,
NBR_MMS_SENT                  NUMBER NOT NULL,
NBR_MMS_SENT_BY_TERMINAL      NUMBER NOT NULL,
NBR_MMS_SENT_BY_APP           NUMBER NOT NULL,
NBR_MMS_RECEIVED_BY_TERMINAL  NUMBER NOT NULL,
NBR_MMSC_FWR_TO_OTHER_MMSC	  NUMBER NOT NULL,
NBR_MMSC_FWR_REC_FROM_MMSC    NUMBER NOT NULL,
NBR_TERM_TO_TERM              NUMBER NOT NULL,
NBR_TERM_TO_APP               NUMBER NOT NULL,
TIME_OF_PERIOD                VARCHAR2(13 CHAR),
FECHA_PROC                    VARCHAR2(8 CHAR)
)NOLOGGING NOCOMPRESS
TABLESPACE DEVELOPER;
--TABLESPACE TBS_AUXILIAR;
--
-- AUX TABLE
--
--
DROP TABLE MMSC_SERVICE_ZTE_AUX;
CREATE TABLE MMSC_SERVICE_ZTE_AUX (
FECHA                         DATE GENERATED ALWAYS AS (TO_DATE(
                                                        SUBSTR(FECHA_PROC,7,2) ||'.'||
                                                        SUBSTR(FECHA_PROC,5,2) ||'.'||
                                                        SUBSTR(FECHA_PROC,1,4) ||' '||
                                                        SUBSTR(TIME_OF_PERIOD,1,5),'DD.MM.YYYY HH24:MI')-1) VIRTUAL,
PAIS                          VARCHAR2(3 CHAR) NOT NULL,
MMSC                          VARCHAR2(10 CHAR) NOT NULL,
NBR_MMS_SENT                  NUMBER NOT NULL,
NBR_MMS_SENT_BY_TERMINAL      NUMBER NOT NULL,
NBR_MMS_SENT_BY_APP           NUMBER NOT NULL,
NBR_MMS_RECEIVED_BY_TERMINAL  NUMBER NOT NULL,
NBR_MMSC_FWR_TO_OTHER_MMSC	  NUMBER NOT NULL,
NBR_MMSC_FWR_REC_FROM_MMSC    NUMBER NOT NULL,
NBR_TERM_TO_TERM              NUMBER NOT NULL,
NBR_TERM_TO_APP               NUMBER NOT NULL,
TIME_OF_PERIOD                VARCHAR2(13 CHAR),
FECHA_PROC                    VARCHAR2(8 CHAR),
NOMBRE_CSV                    VARCHAR2(500 CHAR)
)NOLOGGING NOCOMPRESS
TABLESPACE DEVELOPER;
--TABLESPACE TBS_AUXILIAR;

merge into MMSC_SERVICE_ZTE_AUX AUX
USING (SELECT FECHA,
              PAIS,
              MMSC,
              NBR_MMS_SENT,
              NBR_MMS_SENT_BY_TERMINAL,
              NBR_MMS_SENT_BY_APP,
              NBR_MMS_RECEIVED_BY_TERMINAL,
              NBR_MMSC_FWR_TO_OTHER_MMSC,
              NBR_MMSC_FWR_REC_FROM_MMSC,
              NBR_TERM_TO_TERM,
              NBR_TERM_TO_APP,
              TIME_OF_PERIOD,
              FECHA_PROC
        FROM MMSC_SERVICE_ZTE_TMP) TMP
ON (AUX.FECHA = TMP.FECHA AND AUX.PAIS = TMP.PAIS AND AUX.MMSC = TMP.MMSC AND AUX.TIME_OF_PERIOD = TMP.TIME_OF_PERIOD)
--WHEN MATCHED THEN
--  UPDATE SET
--    AUX.NBR_MMS_SENT                  = TMP.NBR_MMS_SENT,
--    AUX.NBR_MMS_SENT_BY_TERMINAL      = TMP.NBR_MMS_SENT_BY_TERMINAL,
--    AUX.NBR_MMS_SENT_BY_APP           = TMP.NBR_MMS_SENT_BY_APP,
--    AUX.NBR_MMS_RECEIVED_BY_TERMINAL  = TMP.NBR_MMS_RECEIVED_BY_TERMINAL,
--    AUX.NBR_MMSC_FWR_TO_OTHER_MMSC    = TMP.NBR_MMSC_FWR_TO_OTHER_MMSC,
--    AUX.NBR_MMSC_FWR_REC_FROM_MMSC    = TMP.NBR_MMSC_FWR_REC_FROM_MMSC,
--    AUX.NBR_TERM_TO_TERM              = TMP.NBR_TERM_TO_TERM,
--    AUX.NBR_TERM_TO_APP               = TMP.NBR_TERM_TO_APP
WHEN NOT MATCHED THEN
  INSERT(PAIS,MMSC,NBR_MMS_SENT,NBR_MMS_SENT_BY_TERMINAL,NBR_MMS_SENT_BY_APP,NBR_MMS_RECEIVED_BY_TERMINAL,
        NBR_MMSC_FWR_TO_OTHER_MMSC,NBR_MMSC_FWR_REC_FROM_MMSC,NBR_TERM_TO_TERM,NBR_TERM_TO_APP,TIME_OF_PERIOD,FECHA_PROC) 
  VALUES (--TMP.FECHA,
              TMP.PAIS,
              TMP.MMSC,
              TMP.NBR_MMS_SENT,
              TMP.NBR_MMS_SENT_BY_TERMINAL,
              TMP.NBR_MMS_SENT_BY_APP,
              TMP.NBR_MMS_RECEIVED_BY_TERMINAL,
              TMP.NBR_MMSC_FWR_TO_OTHER_MMSC,
              TMP.NBR_MMSC_FWR_REC_FROM_MMSC,
              TMP.NBR_TERM_TO_TERM,
              TMP.NBR_TERM_TO_APP,
              TMP.TIME_OF_PERIOD,
              TMP.FECHA_PROC);

--
--HOUR
-- 
DROP TABLE MMSC_SERVICE_ZTE_HOUR PURGE;
CREATE TABLE MMSC_SERVICE_ZTE_HOUR (
FECHA                         DATE NOT NULL,
PAIS                          VARCHAR2(3 CHAR) NOT NULL,
MMSC                          VARCHAR2(10 CHAR) NOT NULL,
NBR_MMS_SENT                  NUMBER NOT NULL,
NBR_MMS_SENT_BY_TERMINAL      NUMBER NOT NULL,
NBR_MMS_SENT_BY_APP           NUMBER NOT NULL,
NBR_MMS_RECEIVED_BY_TERMINAL  NUMBER NOT NULL,
NBR_MMSC_FWR_TO_OTHER_MMSC	  NUMBER NOT NULL,
NBR_MMSC_FWR_REC_FROM_MMSC    NUMBER NOT NULL,
NBR_TERM_TO_TERM              NUMBER NOT NULL,
NBR_TERM_TO_APP               NUMBER NOT NULL
)NOLOGGING NOCOMPRESS
PARTITION BY RANGE (FECHA)
INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
(
PARTITION MMSC_SERVICE_ZTE_H_FIRST VALUES LESS THAN (TO_DATE('2017-03-20 00:00:00','SYYYY-MM-DD HH24:MI:SS'))
)
TABLESPACE DEVELOPER;
-- TABLESPACE TBS_HOUR;

CREATE INDEX IDX_MMSC_SERVICE_ZTE ON MMSC_SERVICE_ZTE_HOUR(FECHA,PAIS,MMSC) LOCAL 
TABLESPACE DEVELOPER;
--TABLESPACE TBS_HOUR;
CREATE INDEX IDX_MMSC_SERVICE_ZTE_F ON MMSC_SERVICE_ZTE_HOUR(TO_CHAR(FECHA,'DD.MM.YYYY')) LOCAL 
TABLESPACE DEVELOPER;
--TABLESPACE TBS_HOUR;
CREATE INDEX IDX_MMSC_SERVICE_ZTE_FH ON MMSC_SERVICE_ZTE_HOUR(TO_CHAR(FECHA,'DD.MM.YYYY HH24')) LOCAL 
TABLESPACE DEVELOPER;
--TABLESPACE TBS_HOUR;

COMMENT ON COLUMN MMSC_SERVICE_ZTE_HOUR.PAIS                          IS 'Renombrado columna COUNTRY';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_HOUR.FECHA                         IS 'Renombrado columna TIME OF PERIOD';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_HOUR.NBR_MMS_SENT                  IS 'Total number of sent MMSs(O CDR total number (FO is not included))';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_HOUR.NBR_MMS_SENT_BY_TERMINAL      IS 'Number of MMSs sent by terminal';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_HOUR.NBR_MMS_RECEIVED_BY_TERMINAL  IS 'Number of MMSs received by terminal';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_HOUR.NBR_MMS_SENT_BY_APP           IS 'Number of MMSs sent by application';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_HOUR.NBR_MMSC_FWR_TO_OTHER_MMSC    IS 'Number of forwarding to other MMSC';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_HOUR.NBR_MMSC_FWR_REC_FROM_MMSC    IS 'Number of forwarding received from other MMSC';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_HOUR.NBR_TERM_TO_TERM              IS 'Number from terminal to terminal';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_HOUR.NBR_TERM_TO_APP               IS 'Number from terminal to application';

--
-- DAY
--
DROP TABLE MMSC_SERVICE_ZTE_DAY PURGE;
CREATE TABLE MMSC_SERVICE_ZTE_DAY (
FECHA                         DATE NOT NULL,
PAIS                          VARCHAR2(3 CHAR) NOT NULL,
MMSC                          VARCHAR2(10 CHAR) NOT NULL,
NBR_MMS_SENT                  NUMBER NOT NULL,
NBR_MMS_SENT_BY_TERMINAL      NUMBER NOT NULL,
NBR_MMS_SENT_BY_APP           NUMBER NOT NULL,
NBR_MMS_RECEIVED_BY_TERMINAL  NUMBER NOT NULL,
NBR_MMSC_FWR_TO_OTHER_MMSC	  NUMBER NOT NULL,
NBR_MMSC_FWR_REC_FROM_MMSC    NUMBER NOT NULL,
NBR_TERM_TO_TERM              NUMBER NOT NULL,
NBR_TERM_TO_APP               NUMBER NOT NULL
)NOLOGGING NOCOMPRESS
PARTITION BY RANGE (FECHA)
INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
(
PARTITION MMSC_SERVICE_ZTE_D_FIRST VALUES LESS THAN (TO_DATE('2017-03-20 00:00:00','SYYYY-MM-DD HH24:MI:SS'))
)
TABLESPACE DEVELOPER;
-- TABLESPACE TBS_DAY;

CREATE INDEX IDX_MMSC_SERVICE_ZTE_D ON MMSC_SERVICE_ZTE_DAY(FECHA,PAIS,MMSC) LOCAL 
TABLESPACE DEVELOPER;
--TABLESPACE TBS_DAY;
CREATE INDEX IDX_MMSC_SERVICE_ZTE_D_F ON MMSC_SERVICE_ZTE_DAY(TO_CHAR(FECHA,'DD.MM.YYYY')) LOCAL 
TABLESPACE DEVELOPER;
--TABLESPACE TBS_DAY;
CREATE INDEX IDX_MMSC_SERVICE_ZTE_D_FH ON MMSC_SERVICE_ZTE_DAY(TO_CHAR(FECHA,'DD.MM.YYYY HH24')) LOCAL 
TABLESPACE DEVELOPER;
--TABLESPACE TBS_DAY;

COMMENT ON COLUMN MMSC_SERVICE_ZTE_DAY.PAIS                          IS 'Renombrado columna COUNTRY';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_DAY.FECHA                         IS 'Renombrado columna TIME OF PERIOD';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_DAY.NBR_MMS_SENT                  IS 'Total number of sent MMSs(O CDR total number (FO is not included))';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_DAY.NBR_MMS_SENT_BY_TERMINAL      IS 'Number of MMSs sent by terminal';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_DAY.NBR_MMS_RECEIVED_BY_TERMINAL  IS 'Number of MMSs received by terminal';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_DAY.NBR_MMS_SENT_BY_APP           IS 'Number of MMSs sent by application';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_DAY.NBR_MMSC_FWR_TO_OTHER_MMSC    IS 'Number of forwarding to other MMSC';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_DAY.NBR_MMSC_FWR_REC_FROM_MMSC    IS 'Number of forwarding received from other MMSC';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_DAY.NBR_TERM_TO_TERM              IS 'Number from terminal to terminal';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_DAY.NBR_TERM_TO_APP               IS 'Number from terminal to application';

--
-- BH
--
DROP TABLE MMSC_SERVICE_ZTE_BH PURGE;
CREATE TABLE MMSC_SERVICE_ZTE_BH (
FECHA                         DATE NOT NULL,
PAIS                          VARCHAR2(3 CHAR) NOT NULL,
MMSC                          VARCHAR2(10 CHAR) NOT NULL,
NBR_MMS_SENT                  NUMBER NOT NULL,
NBR_MMS_SENT_BY_TERMINAL      NUMBER NOT NULL,
NBR_MMS_SENT_BY_APP           NUMBER NOT NULL,
NBR_MMS_RECEIVED_BY_TERMINAL  NUMBER NOT NULL,
NBR_MMSC_FWR_TO_OTHER_MMSC	  NUMBER NOT NULL,
NBR_MMSC_FWR_REC_FROM_MMSC    NUMBER NOT NULL,
NBR_TERM_TO_TERM              NUMBER NOT NULL,
NBR_TERM_TO_APP               NUMBER NOT NULL
)NOLOGGING NOCOMPRESS
PARTITION BY RANGE (FECHA)
INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
(
PARTITION MMSC_SERVICE_ZTE_BH_FIRST VALUES LESS THAN (TO_DATE('2017-03-20 00:00:00','SYYYY-MM-DD HH24:MI:SS'))
)
TABLESPACE DEVELOPER;
-- TABLESPACE TBS_DAY;

CREATE INDEX IDX_MMSC_SERVICE_ZTE_BH ON MMSC_SERVICE_ZTE_BH(FECHA,PAIS,MMSC) LOCAL 
TABLESPACE DEVELOPER;
--TABLESPACE TBS_DAY;
CREATE INDEX IDX_MMSC_SERVICE_ZTE_BH_F ON MMSC_SERVICE_ZTE_BH(TO_CHAR(FECHA,'DD.MM.YYYY')) LOCAL 
TABLESPACE DEVELOPER;
--TABLESPACE TBS_DAY;
CREATE INDEX IDX_MMSC_SERVICE_ZTE_BH_FH ON MMSC_SERVICE_ZTE_BH(TO_CHAR(FECHA,'DD.MM.YYYY HH24')) LOCAL 
TABLESPACE DEVELOPER;
--TABLESPACE TBS_DAY;

COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.PAIS                          IS 'Renombrado columna COUNTRY';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.FECHA                         IS 'Renombrado columna TIME OF PERIOD';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_MMS_SENT                  IS 'Total number of sent MMSs(O CDR total number (FO is not included))';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_MMS_SENT_BY_TERMINAL      IS 'Number of MMSs sent by terminal';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_MMS_RECEIVED_BY_TERMINAL  IS 'Number of MMSs received by terminal';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_MMS_SENT_BY_APP           IS 'Number of MMSs sent by application';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_MMSC_FWR_TO_OTHER_MMSC    IS 'Number of forwarding to other MMSC';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_MMSC_FWR_REC_FROM_MMSC    IS 'Number of forwarding received from other MMSC';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_TERM_TO_TERM              IS 'Number from terminal to terminal';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_TERM_TO_APP               IS 'Number from terminal to application';

--
-- IBHW
--
DROP TABLE MMSC_SERVICE_ZTE_IBHW PURGE;
CREATE TABLE MMSC_SERVICE_ZTE_IBHW (
FECHA                         DATE NOT NULL,
PAIS                          VARCHAR2(3 CHAR) NOT NULL,
MMSC                          VARCHAR2(10 CHAR) NOT NULL,
NBR_MMS_SENT                  NUMBER NOT NULL,
NBR_MMS_SENT_BY_TERMINAL      NUMBER NOT NULL,
NBR_MMS_SENT_BY_APP           NUMBER NOT NULL,
NBR_MMS_RECEIVED_BY_TERMINAL  NUMBER NOT NULL,
NBR_MMSC_FWR_TO_OTHER_MMSC	  NUMBER NOT NULL,
NBR_MMSC_FWR_REC_FROM_MMSC    NUMBER NOT NULL,
NBR_TERM_TO_TERM              NUMBER NOT NULL,
NBR_TERM_TO_APP               NUMBER NOT NULL
)NOLOGGING NOCOMPRESS
PARTITION BY RANGE (FECHA)
INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
(
PARTITION MMSC_SERVICE_ZTE_IBHW_FIRST VALUES LESS THAN (TO_DATE('2017-03-20 00:00:00','SYYYY-MM-DD HH24:MI:SS'))
)
TABLESPACE DEVELOPER;
-- TABLESPACE TBS_SUMMARY;

CREATE INDEX IDX_MMSC_SERVICE_ZTE_IBHW ON MMSC_SERVICE_ZTE_IBHW(FECHA,PAIS,MMSC) LOCAL 
TABLESPACE DEVELOPER;
--TABLESPACE TBS_SUMMARY;
CREATE INDEX IDX_MMSC_SERVICE_ZTE_IBHW_F ON MMSC_SERVICE_ZTE_IBHW(TO_CHAR(FECHA,'DD.MM.YYYY')) LOCAL 
TABLESPACE DEVELOPER;
--TABLESPACE TBS_SUMMARY;
CREATE INDEX IDX_MMSC_SERVICE_ZTE_IBHW_FH ON MMSC_SERVICE_ZTE_IBHW(TO_CHAR(FECHA,'DD.MM.YYYY HH24')) LOCAL 
TABLESPACE DEVELOPER;
--TABLESPACE TBS_SUMMARY;

COMMENT ON COLUMN MMSC_SERVICE_ZTE_IBHW.PAIS                          IS 'Renombrado columna COUNTRY';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_IBHW.FECHA                         IS 'Renombrado columna TIME OF PERIOD';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_IBHW.NBR_MMS_SENT                  IS 'Total number of sent MMSs(O CDR total number (FO is not included))';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_IBHW.NBR_MMS_SENT_BY_TERMINAL      IS 'Number of MMSs sent by terminal';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_IBHW.NBR_MMS_RECEIVED_BY_TERMINAL  IS 'Number of MMSs received by terminal';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_IBHW.NBR_MMS_SENT_BY_APP           IS 'Number of MMSs sent by application';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_IBHW.NBR_MMSC_FWR_TO_OTHER_MMSC    IS 'Number of forwarding to other MMSC';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_IBHW.NBR_MMSC_FWR_REC_FROM_MMSC    IS 'Number of forwarding received from other MMSC';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_IBHW.NBR_TERM_TO_TERM              IS 'Number from terminal to terminal';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_IBHW.NBR_TERM_TO_APP               IS 'Number from terminal to application';
