
CREATE TABLE MMSC_REPORT_KPI_ZTE_DAY(
  FECHA           DATE NOT NULL,
  PAIS            VARCHAR2(20 CHAR) NOT NULL,
  MMSC            VARCHAR2(10 CHAR) NOT NULL,
  NBR_SENT_MMS    NUMBER NOT NULL,
  NBR_SENT_MMS_2  NUMBER NOT NULL,
  NBR_RECEIVED_MMS_2  NUMBER NOT NULL,
  NETWORK_FAILURE_SUBMISSION  NUMBER NOT NULL,
  SUBSCRIBER_FAILURE_SUBMISSION NUMBER NOT NULL,
  NETWORK_FAILURE_DELIVERY      NUMBER NOT NULL,
  SUBSCRIBER_FAILURE_DELIBERY   NUMBER NOT NULL,
  MMS_NET_PROC_COMP_RATIO       NUMBER(12,2) NOT NULL
)NOLOGGING NOCOMPRESS
PARTITION BY RANGE (FECHA)
INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
(
PARTITION MMSC_REPORT_KPI_ZTE_D_FIRST VALUES LESS THAN (TO_DATE('2017-03-20 00:00:00','SYYYY-MM-DD HH24:MI:SS'))
)
TABLESPACE DEVELOPER;
-- TABLESPACE TBS_DAY;

COMMENT ON COLUMN MMSC_REPORT_KPI_ZTE_DAY.PAIS                          IS 'Renombrado columna Country';
COMMENT ON COLUMN MMSC_REPORT_KPI_ZTE_DAY.FECHA                         IS 'Renombrado columna Date';
COMMENT ON COLUMN MMSC_REPORT_KPI_ZTE_DAY.NBR_SENT_MMS                  IS 'Total number of sent MMSs(O CDR total number (FO is not included))';
COMMENT ON COLUMN MMSC_REPORT_KPI_ZTE_DAY.NBR_SENT_MMS_2                IS 'Total number of sent MMSs-2(O CDR total number (FO is  included))';
COMMENT ON COLUMN MMSC_REPORT_KPI_ZTE_DAY.NBR_RECEIVED_MMS_2            IS 'Total number of received MMSs-2(T CDR total number(FT is included))';
COMMENT ON COLUMN MMSC_REPORT_KPI_ZTE_DAY.NETWORK_FAILURE_SUBMISSION    IS 'Network failure submission numbers';
COMMENT ON COLUMN MMSC_REPORT_KPI_ZTE_DAY.SUBSCRIBER_FAILURE_SUBMISSION IS 'Subscriber failure submission numbers';
COMMENT ON COLUMN MMSC_REPORT_KPI_ZTE_DAY.NETWORK_FAILURE_DELIVERY      IS 'Network failure delivery numbers';
COMMENT ON COLUMN MMSC_REPORT_KPI_ZTE_DAY.SUBSCRIBER_FAILURE_DELIBERY   IS 'Subscriber failure delivery numbers';
COMMENT ON COLUMN MMSC_REPORT_KPI_ZTE_DAY.MMS_NET_PROC_COMP_RATIO       IS 'MMS network whole process completion ratio(%)';