/*
MMSC_License_KPI_ZTE	WAP GATEWAY	MMSC	TEXTO
		

*/
CREATE TABLE MMSC_LICENSE_KPI_ZTE_DAY(
  FECHA                     DATE NOT NULL,
  MMSC                      VARCHAR2(10 CHAR) NOT NULL,
  MMS_BUSY_SERVICE_TRAFFIC  NUMBER NOT NULL
)NOCOMPRESS NOLOGGING
PARTITION BY RANGE (FECHA)
INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
(
PARTITION MMSC_LICENSE_KPI_ZTE_D_FIRST VALUES LESS THAN (TO_DATE('2017-03-20 00:00:00','SYYYY-MM-DD HH24:MI:SS'))
)
TABLESPACE DEVELOPER;
-- TABLESPACE TBS_DAY;

COMMENT ON COLUMN MMSC_LICENSE_KPI_ZTE_DAY.FECHA                    IS 'Renombrado columna Date';
COMMENT ON COLUMN MMSC_LICENSE_KPI_ZTE_DAY.MMS_BUSY_SERVICE_TRAFFIC IS 'MMS busy second  service traffic(piece/second)';