--
-- BH
--
CREATE TABLE MMSC_SERVICE_ZTE_BH (
FECHA                         DATE NOT NULL,
PAIS                          VARCHAR2(3 CHAR) NOT NULL,
MMSC                          VARCHAR2(10 CHAR) NOT NULL,
NBR_MMS_SENT                  NUMBER NOT NULL,
NBR_MMS_SENT_BY_TERMINAL      NUMBER NOT NULL,
NBR_MMS_SENT_BY_APP           NUMBER NOT NULL,
NBR_MMS_RECEIVED_BY_TERMINAL  NUMBER NOT NULL,
NBR_MMSC_FWR_TO_OTHER_MMSC    NUMBER NOT NULL,
NBR_MMSC_FWR_REC_FROM_MMSC    NUMBER NOT NULL,
NBR_TERM_TO_TERM              NUMBER NOT NULL,
NBR_TERM_TO_APP               NUMBER NOT NULL
)NOLOGGING NOCOMPRESS
PARTITION BY RANGE (FECHA)
INTERVAL (NUMTODSINTERVAL(1, 'DAY'))
(
PARTITION MMSC_SERVICE_ZTE_BH_FIRST VALUES LESS THAN (TO_DATE('2017-03-20 00:00:00','SYYYY-MM-DD HH24:MI:SS'))
)
TABLESPACE TBS_DAY;

CREATE INDEX IDX_MMSC_SERVICE_ZTE_BH ON MMSC_SERVICE_ZTE_BH(FECHA,PAIS,MMSC) LOCAL 
TABLESPACE TBS_DAY;
CREATE INDEX IDX_MMSC_SERVICE_ZTE_BH_F ON MMSC_SERVICE_ZTE_BH(TO_CHAR(FECHA,'DD.MM.YYYY')) LOCAL 
TABLESPACE TBS_DAY;
CREATE INDEX IDX_MMSC_SERVICE_ZTE_BH_FH ON MMSC_SERVICE_ZTE_BH(TO_CHAR(FECHA,'DD.MM.YYYY HH24')) LOCAL 
TABLESPACE TBS_DAY;

COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.PAIS                          IS 'Renombrado columna COUNTRY';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.FECHA                         IS 'Renombrado columna TIME OF PERIOD';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_MMS_SENT                  IS 'Total number of sent MMSs(O CDR total number (FO is not included))';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_MMS_SENT_BY_TERMINAL      IS 'Number of MMSs sent by terminal';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_MMS_RECEIVED_BY_TERMINAL  IS 'Number of MMSs received by terminal';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_MMS_SENT_BY_APP           IS 'Number of MMSs sent by application';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_MMSC_FWR_TO_OTHER_MMSC    IS 'Number of forwarding to other MMSC';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_MMSC_FWR_REC_FROM_MMSC    IS 'Number of forwarding received from other MMSC';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_TERM_TO_TERM              IS 'Number from terminal to terminal';
COMMENT ON COLUMN MMSC_SERVICE_ZTE_BH.NBR_TERM_TO_APP               IS 'Number from terminal to application';
